In [3]:
#1 prime no
a=int(input())
c=0
for i in range(1,a+1):
    if(a%i==0):
        c=c+1
if(c==2):
    print("it is a prime number")
else:
    print("not a prime number")

10
not a prime number


In [4]:
#2 sum of prime no between 1 to 100
for i in range(1,101):
    c=0
    for j in range(1,i+1):
        if(i%j==0):
            c=c+1
    if(c==2):
        print(i,end=",")

2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97,

In [7]:
#3 factorial and sum of digit
n=int(input())
f=1
for i in range(1,n+1):
    f=f*i
print("factorial of a number=",f)
s=0
while(f):
    s+=f%10
    f=f//10
print("sum of digit=",s)

7
factorial of a number= 5040
sum of digit= 9


In [10]:
#4 fibonacci series
n=int(input())
a=0 
b=1
print(a,b,end=" ")
c=0
for i in range(n-2):
    c=a+b
    print(c,end=" ")
    a=b
    b=c

10
0 1 1 2 3 5 8 13 21 34 

In [11]:
#5 even fibonacci series
n=int(input())
a=0 
b=1
print(a,end=" ")
c=0
for i in range(n-2):
    c=a+b
    if(c%2==0):
        print(c,end=" ")
    a=b
    b=c

10
0 2 8 34 

In [17]:
#6 square root of a number
import math
n=int(input())
print(pow(n,1/2))

16
4.0


In [47]:
#7 Display calender
import calendar
print(calendar.month(2019,12))

   December 2019
Mo Tu We Th Fr Sa Su
                   1
 2  3  4  5  6  7  8
 9 10 11 12 13 14 15
16 17 18 19 20 21 22
23 24 25 26 27 28 29
30 31



In [20]:
#8 Display a matrix
import numpy as np
print(np.matrix("1,2,3;4,5,6;7,8,9"))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
#9 addition of two square matrices
import numpy as np
print(np.array([[1,2],[3,4]])+np.matrix([[5,6],[7,8]]))

[[ 6  8]
 [10 12]]


In [25]:
#10 multiplication of two 5X4 matrices
import numpy as np
print(np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])*np.array([[5,6,7,8],[5,6,7,8],[5,6,7,8],[5,6,7,8],[5,6,7,8]]))

[[ 5 12 21 32]
 [ 5 12 21 32]
 [ 5 12 21 32]
 [ 5 12 21 32]
 [ 5 12 21 32]]


In [30]:
#11 distance between two points
x1,x2,y1,y2=map(int,input().split())
print(((x1-x2)**2+(y1-y2)**2)**(1/2))

1 3 1 3
2.8284271247461903


In [33]:
#12 count no of characters in a string and store them in a dictionary
s=input()
c=0
dic={}
for i in range(len(s)):
    c=c+1
    dic[i]=s[i]
print("counter of character=",c)
print(dic)

shailesh
counter of character= 8
{0: 's', 1: 'h', 2: 'a', 3: 'i', 4: 'l', 5: 'e', 6: 's', 7: 'h'}


In [44]:
#13 Ball is colliding or not
def colliding(t1,t2):
    q=((t1[0]-t2[0])**2+(t1[1]-t2[1])**2)**(1/2)
    s=t1[2]+t2[2]
    if(q<=s):
        print("they are colliding")
    else:
        print("they are not colliding")
colliding((1,2,3),(4,5,2))

they are colliding


In [45]:
#14 reverse a list
def rev(l):
    print(l[::-1])
rev([1,2,3])

[3, 2, 1]


In [50]:
#15 find all duplicates in a list
def dups(l):
    li=[]
    for i in l:
        if(l.count(i)>1):
            if(i not in li):
                li.append(i)
    print(*li)
dups([1,2,3,1,2,4,1,5,3,4,5,6,7])

1 2 3 4 5


In [55]:
#16 area of a triangle
def area(a,b,c):
    s=(a+b+c)/2
    print((s*(s-a)*(s-b)*(s-c))**(1/2))
a,b,c=map(int,input().split())
area(a,b,c)

5 9 7
17.41228014936585


In [61]:
#17 2d array contains b/w 5 and 10
import numpy as np
import random
a=np.array([[0,0,0],[0,0,0],[0,0,0]])
for i in range(3):
    for j in range(3):
        a[i][j]=random.randrange(5,10)
print(a)

[[9 8 6]
 [8 7 5]
 [5 5 5]]


In [63]:
#18 save data of a student in a json file
import json
my_details = {
    'name': 'John Doe','age': 29,'roll':12,'phone':7896541278,'dob':'3/12/1999'}
with open('personal.json', 'w') as json_file:
    json.dump(my_details, json_file)

In [71]:
#19 store frequency of each character in a file
f=open("python.txt",'w')
f.write("hello world and what is my name i dont know")
f.close()
f=open("python.txt",'r')
x=f.read()
x.replace("\n"," ")
l=[]
for i in x:
    l.append(i)
li=[]
dic={}
for i in l:
    if(i==" "):
        continue
    if(i not in li):
        li.append(i)
        dic[i]=l.count(i)
print(dic)

{'h': 2, 'e': 2, 'l': 3, 'o': 4, 'w': 3, 'r': 1, 'd': 3, 'a': 3, 'n': 4, 't': 2, 'i': 2, 's': 1, 'm': 2, 'y': 1, 'k': 1}


In [85]:
#20 store frequency of each character in a file
import sys
f=open("python1.txt",'w')
try:
    s=input()
except ValueError:
    print("reenter the correct data")
    sys.exit()
f.write(s)
f.close()
f=open("python1.txt",'r')
x=f.read()
x.replace("\n"," ")
l=[]
for i in x:
    l.append(i)
li=[]
dic={}
for i in l:
    if(i==" "):
        continue
    if(i not in li):
        li.append(i)
        dic[i]=l.count(i)
print(dic)

hello world
{'h': 1, 'e': 1, 'l': 3, 'o': 2, 'w': 1, 'r': 1, 'd': 1}
